/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExportRouteImport } from './routes/export'
import { Route as UsersRouteImport } from './routes/users'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as PProjectIdIndexRouteImport } from './routes/p.$projectId.index'
import { Route as PProjectIdProgressRouteImport } from './routes/p.$projectId.progress'
import { Route as PProjectIdReviewRouteImport } from './routes/p.$projectId.review'
import { Route as PProjectIdSetupRouteImport } from './routes/p.$projectId.setup'
import { Route as PProjectIdTasksRouteImport } from './routes/p.$projectId.tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdProgressRoute = PProjectIdProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdReviewRoute = PProjectIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdSetupRoute = PProjectIdSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdTasksRoute = PProjectIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => PProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/users': typeof UsersRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/p/$projectId/progress': typeof PProjectIdProgressRoute
  '/p/$projectId/review': typeof PProjectIdReviewRoute
  '/p/$projectId/setup': typeof PProjectIdSetupRoute
  '/p/$projectId/tasks': typeof PProjectIdTasksRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/users': typeof UsersRoute
  '/p/$projectId/progress': typeof PProjectIdProgressRoute
  '/p/$projectId/review': typeof PProjectIdReviewRoute
  '/p/$projectId/setup': typeof PProjectIdSetupRoute
  '/p/$projectId/tasks': typeof PProjectIdTasksRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/users': typeof UsersRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/p/$projectId/progress': typeof PProjectIdProgressRoute
  '/p/$projectId/review': typeof PProjectIdReviewRoute
  '/p/$projectId/setup': typeof PProjectIdSetupRoute
  '/p/$projectId/tasks': typeof PProjectIdTasksRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/auth'
    | '/dashboard'
    | '/export'
    | '/users'
    | '/p/$projectId'
    | '/p/$projectId/progress'
    | '/p/$projectId/review'
    | '/p/$projectId/setup'
    | '/p/$projectId/tasks'
    | '/p/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/auth'
    | '/dashboard'
    | '/export'
    | '/users'
    | '/p/$projectId/progress'
    | '/p/$projectId/review'
    | '/p/$projectId/setup'
    | '/p/$projectId/tasks'
    | '/p/$projectId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/auth'
    | '/dashboard'
    | '/export'
    | '/users'
    | '/p/$projectId'
    | '/p/$projectId/progress'
    | '/p/$projectId/review'
    | '/p/$projectId/setup'
    | '/p/$projectId/tasks'
    | '/p/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ExportRoute: typeof ExportRoute
  UsersRoute: typeof UsersRoute
  PProjectIdRoute: typeof PProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/progress': {
      id: '/p/$projectId/progress'
      path: '/progress'
      fullPath: '/p/$projectId/progress'
      preLoaderRoute: typeof PProjectIdProgressRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/review': {
      id: '/p/$projectId/review'
      path: '/review'
      fullPath: '/p/$projectId/review'
      preLoaderRoute: typeof PProjectIdReviewRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/setup': {
      id: '/p/$projectId/setup'
      path: '/setup'
      fullPath: '/p/$projectId/setup'
      preLoaderRoute: typeof PProjectIdSetupRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/tasks': {
      id: '/p/$projectId/tasks'
      path: '/tasks'
      fullPath: '/p/$projectId/tasks'
      preLoaderRoute: typeof PProjectIdTasksRouteImport
      parentRoute: typeof PProjectIdRoute
    }
  }
}

interface PProjectIdRouteChildren {
  PProjectIdProgressRoute: typeof PProjectIdProgressRoute
  PProjectIdReviewRoute: typeof PProjectIdReviewRoute
  PProjectIdSetupRoute: typeof PProjectIdSetupRoute
  PProjectIdTasksRoute: typeof PProjectIdTasksRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
}

const PProjectIdRouteChildren: PProjectIdRouteChildren = {
  PProjectIdProgressRoute: PProjectIdProgressRoute,
  PProjectIdReviewRoute: PProjectIdReviewRoute,
  PProjectIdSetupRoute: PProjectIdSetupRoute,
  PProjectIdTasksRoute: PProjectIdTasksRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
}

const PProjectIdRouteWithChildren = PProjectIdRoute._addFileChildren(
  PProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ExportRoute: ExportRoute,
  UsersRoute: UsersRoute,
  PProjectIdRoute: PProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
